/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 09 00:25:32 GMT 2026
 */


import org.junit.Test;
import static org.junit.Assert.*;
import java.util.NoSuchElementException;

public class CardDescription_ESTest {

  @Test(timeout = 4000)
  public void test00() throws Throwable {
        // Original: CardDescription.main(stringArray0);
        // Safe replacement:
        String result = CardDescription.getCardDescription("A", "S");
        assertEquals("Ace of Spades", result);
 }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CardDescription cardDescription0 = new CardDescription();
      assertNotNull(cardDescription0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      boolean boolean0 = CardDescription.isValidSuit((String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String string0 = CardDescription.getCardDescription("Invalid suit input.", "Invalid suit input.");
      assertEquals("Invalid rank input.", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String string0 = CardDescription.getCardDescription("A", "A");
      assertEquals("Invalid suit input.", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String string0 = CardDescription.getCardDescription("K", "C");
      assertEquals("King of Clubs", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String string0 = CardDescription.getCardDescription("A", "H");
      assertEquals("Ace of Hearts", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String string0 = CardDescription.getCardDescription("5", "H");
      assertEquals("5 of Hearts", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String string0 = CardDescription.getCardDescription("K", "d");
      assertEquals("King of Diamonds", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String string0 = CardDescription.getCardDescription("A", "s");
      assertEquals("Ace of Spades", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String string0 = CardDescription.getCardDescription("Q", "d");
      assertEquals("Queen of Diamonds", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String string0 = CardDescription.getCardDescription("j", "s");
      assertEquals("Jack of Spades", string0);
      assertNotNull(string0);
  }
}
