from app.infrastructure.models import CheckstyleViolation
import xml.etree.ElementTree as ET

def parse_checkstyle(xml_text: str) -> list[CheckstyleViolation]:
    """parses the raw xml report generated by the CheckStyle tool

    Args:
        xml_text (str): the xml content as String

    Returns:
        list[CheckstyleViolation]: list of CheckStyle violations
    """
    try:
        root = ET.fromstring(xml_text)  # get tree root from txt file
        errors: list[CheckstyleViolation] = []
        
        for file_element in root.findall('file'):
 
            for error in file_element.findall('error'):
                source = error.attrib.get("source", "")
                parts = source.split(".")
                # split the string to get second to last part, i.e the violation category if existent
                category = parts[-2] if len(parts) >= 7 else None
                # split the string to get the last part, i.e the specific violation type
                type_name = parts[-1] if len(parts) >= 1 else source
                
                errors.append(
                    CheckstyleViolation(
                        file_name = file_element.attrib.get("name", ""),
                        line = int(error.attrib.get('line', "0")),
                        severity = error.attrib.get("severity", ""),
                        category = category,
                        type_name = type_name,
                        message = error.attrib.get("message", "")
                    )
                )
        return errors
    
    except ET.ParseError as e:
        print(f"Failed to parse XML: {e}")
        return []