from app.infrastructure.models import (
    UnitTestCase, 
    UnitTestingResults, 
    UnitTestingSummary, 
    TestFailureDetails
)
import xml.etree.ElementTree as ET
import sys

def parse_test_results_xml(junit_xml: str) -> UnitTestingResults:
    """parses the xml junit report generated by the tool

    Args:
        junit_xml (str): the xml contents

    Returns:
        UnitTestingResults: object containing the parsed report info
    """
    try:
        root = ET.fromstring(junit_xml)
        if root.tag == 'testsuite':
            summary_ele = root
            testcases = root.findall('testcase')
        else:
            summary_ele = root.find('testsuite')
            testcases = summary_ele.findall('testcase')
        
        summary = UnitTestingSummary()
        result = UnitTestingResults(summary = summary, testcases = [], test_suite = "")
        
        summary.tests_ran = int(summary_ele.attrib.get('tests', 0))
        summary.failures = int(summary_ele.attrib.get('failures', 0))
        summary.errors = int(summary_ele.attrib.get('errors', 0))
        summary.skipped = int(summary_ele.attrib.get('skipped', 0))
        summary.time_elapsed = summary_ele.attrib.get('time', 0.0)
        
        for unit_test_ele in testcases:
            time_taken = unit_test_ele.attrib.get('time')
            case_name = unit_test_ele.attrib.get('name')
            
            test_case = UnitTestCase(
                name = case_name, 
                time = time_taken, 
                status = 'PASSED'
            )
            
            failure = unit_test_ele.find('failure')
            error = unit_test_ele.find('error')
            skipped = unit_test_ele.find('skipped')
            
            if skipped is not None:
                test_case.status = 'SKIPPED'
                result.testcases.append(test_case)
                continue
            
            if failure is not None or error is not None:
                test_case.status = 'FAILED'
                issue = failure if failure is not None else error
                
                msg = issue.attrib.get('message')
                stack_trace = issue.text.strip() if issue.text else ""
                
                test_case.failure_details = TestFailureDetails(
                    message = msg, 
                    stack_trace = stack_trace
                )
            
            result.testcases.append(test_case)
        
        return result
    
    except ET.ParseError as e:
        print(f"Failed to parse XML: {e}", file=sys.stderr)
        return None
        
def parse_test_results_txt(junit_txt: str) -> UnitTestingResults:
    """parses the junit test result txt file

    Args:
        junit_txt (str): junit result file content as String

    Raises:
        ValueError: if format invalid

    Returns:
        UnitTestingResults: structure containing the summary, list of testcases, and test_suite
    """
    try:
        current_test_case: UnitTestCase | None = None
        summary = UnitTestingSummary()
        result = UnitTestingResults(summary = summary, testcases = [], test_suite = "")

        # Parse the file line by line
        for line in junit_txt.splitlines():
            
            line = line.strip()
            
            if line.startswith("Testsuite:"):
                result.test_suite = line.split(":")[1].strip()
                
            elif line.startswith("Tests run:"):
                parts = line.split(", ")
                summary.tests_ran = int(parts[0].split(":")[1].strip())
                summary.failures = int(parts[1].split(":")[1].strip())
                summary.errors = int(parts[2].split(":")[1].strip())
                summary.skipped = int(parts[3].split(":")[1].strip())
                summary.time_elapsed = parts[4].split(":")[1].strip()
                
            elif line.startswith("Testcase:"):
                
                if current_test_case is not None: # to avoid storing the default None value in the first iteration
                    result.testcases.append(current_test_case) # storing parsed testcase from previous iteration
                    
                parts = line.split(" took ")
                test_case_name = parts[0].split(":")[1].strip()
                time_taken = parts[1].strip()
                
                current_test_case = UnitTestCase(
                    name = test_case_name,
                    time = time_taken,
                    status = "PASSED" 
                )
                
            elif line.startswith("FAILED") and current_test_case:
                current_test_case.status = "FAILED"
                current_test_case.failure_details = TestFailureDetails()
                
            elif line.startswith("Caused an ERROR") and current_test_case: # define behavior for "Caused an ERROR" case
                current_test_case.status = "ERROR"
                current_test_case.failure_details = TestFailureDetails()
                
            elif line.startswith("expected:") and current_test_case.failure_details:
                current_test_case.failure_details.message = line
                
            elif line.startswith("at ") and current_test_case.failure_details:
                current_test_case.failure_details.stack_trace.append(line)

        # Add the last test case if exists
        if current_test_case:
            result.testcases.append(current_test_case)

        return result
 
    except Exception as e:
        print(f"Failed to parse test results: {e}", file=sys.stderr)
        raise ValueError("Invalid JUnit test output", file=sys.stderr) from e